global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'pugach.prometheus@gmail.com'
  smtp_auth_username: 'pugach.prometheus@gmail.com'
  smtp_auth_password: ''

route:
  receiver: 'telegram'

  routes:
    - match:
        severity: critical
      receiver: 'gmail'

    - match:
        severity: critical
      receiver: 'telegram'

receivers:
- name: 'telegram'
  webhook_configs:
  - send_resolved: true
    url: 'http://telegram:8080'

- name: 'gmail'
  email_configs:
  - to: 'fotone97@yandex.ru'
    send_resolved: true
